// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster_status_response.proto

package models

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeStatus struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Build                string   `protobuf:"bytes,3,opt,name=build,proto3" json:"build,omitempty"`
	StartedAt            string   `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsAvailable          bool     `protobuf:"varint,6,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	IsLive               bool     `protobuf:"varint,7,opt,name=is_live,json=isLive,proto3" json:"is_live,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeStatus) Reset()         { *m = NodeStatus{} }
func (m *NodeStatus) String() string { return proto.CompactTextString(m) }
func (*NodeStatus) ProtoMessage()    {}
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c1179cc8f2c3db0, []int{0}
}

func (m *NodeStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStatus.Unmarshal(m, b)
}
func (m *NodeStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStatus.Marshal(b, m, deterministic)
}
func (m *NodeStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatus.Merge(m, src)
}
func (m *NodeStatus) XXX_Size() int {
	return xxx_messageInfo_NodeStatus.Size(m)
}
func (m *NodeStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatus proto.InternalMessageInfo

func (m *NodeStatus) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeStatus) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NodeStatus) GetBuild() string {
	if m != nil {
		return m.Build
	}
	return ""
}

func (m *NodeStatus) GetStartedAt() string {
	if m != nil {
		return m.StartedAt
	}
	return ""
}

func (m *NodeStatus) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *NodeStatus) GetIsAvailable() bool {
	if m != nil {
		return m.IsAvailable
	}
	return false
}

func (m *NodeStatus) GetIsLive() bool {
	if m != nil {
		return m.IsLive
	}
	return false
}

type MonitoringResponse struct {
	Nodes                []*NodeStatus `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	LastUpdated          string        `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MonitoringResponse) Reset()         { *m = MonitoringResponse{} }
func (m *MonitoringResponse) String() string { return proto.CompactTextString(m) }
func (*MonitoringResponse) ProtoMessage()    {}
func (*MonitoringResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c1179cc8f2c3db0, []int{1}
}

func (m *MonitoringResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitoringResponse.Unmarshal(m, b)
}
func (m *MonitoringResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitoringResponse.Marshal(b, m, deterministic)
}
func (m *MonitoringResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitoringResponse.Merge(m, src)
}
func (m *MonitoringResponse) XXX_Size() int {
	return xxx_messageInfo_MonitoringResponse.Size(m)
}
func (m *MonitoringResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitoringResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MonitoringResponse proto.InternalMessageInfo

func (m *MonitoringResponse) GetNodes() []*NodeStatus {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *MonitoringResponse) GetLastUpdated() string {
	if m != nil {
		return m.LastUpdated
	}
	return ""
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c1179cc8f2c3db0, []int{2}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*NodeStatus)(nil), "models.NodeStatus")
	proto.RegisterType((*MonitoringResponse)(nil), "models.MonitoringResponse")
	proto.RegisterType((*Void)(nil), "models.Void")
}

func init() { proto.RegisterFile("cluster_status_response.proto", fileDescriptor_2c1179cc8f2c3db0) }

var fileDescriptor_2c1179cc8f2c3db0 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xbf, 0x6a, 0xf3, 0x40,
	0x10, 0xc4, 0x3f, 0xf9, 0x8f, 0xfc, 0x79, 0x6d, 0x02, 0x39, 0x02, 0x39, 0x0c, 0x06, 0x47, 0x95,
	0x2a, 0x17, 0x4e, 0x91, 0xda, 0x55, 0x1a, 0x27, 0x85, 0x4c, 0xd2, 0x8a, 0xb3, 0x6f, 0x09, 0x0b,
	0x17, 0x9d, 0xb8, 0x5d, 0xe9, 0x11, 0xf3, 0x5c, 0x41, 0xd2, 0x09, 0x17, 0x29, 0xe7, 0x37, 0x03,
	0xb3, 0x73, 0x07, 0xdb, 0xab, 0x6b, 0x58, 0x30, 0x94, 0x2c, 0x46, 0x1a, 0x2e, 0x03, 0x72, 0xed,
	0x2b, 0xc6, 0x7d, 0x1d, 0xbc, 0x78, 0x95, 0x7e, 0x7b, 0x8b, 0x8e, 0xb3, 0x9f, 0x04, 0xe0, 0xdd,
	0x5b, 0x3c, 0xf7, 0x29, 0x75, 0x07, 0x13, 0xb2, 0x3a, 0xd9, 0x25, 0xf9, 0xb2, 0x98, 0x90, 0x55,
	0x1a, 0x16, 0xc6, 0xda, 0x80, 0xcc, 0x7a, 0xd2, 0xc3, 0x51, 0xaa, 0x07, 0x98, 0x5f, 0x1a, 0x72,
	0x56, 0x4f, 0x7b, 0x3e, 0x08, 0xb5, 0x05, 0x60, 0x31, 0x41, 0xd0, 0x96, 0x46, 0xf4, 0xac, 0xb7,
	0x96, 0x91, 0x1c, 0xa5, 0xb3, 0x9b, 0xda, 0x9a, 0x68, 0xcf, 0x07, 0x3b, 0x92, 0xa3, 0xa8, 0x27,
	0x58, 0x13, 0x97, 0xa6, 0x35, 0xe4, 0xcc, 0xc5, 0xa1, 0x4e, 0x77, 0x49, 0xfe, 0xbf, 0x58, 0x11,
	0x1f, 0x47, 0xa4, 0x1e, 0x61, 0x41, 0x5c, 0x3a, 0x6a, 0x51, 0x2f, 0x7a, 0x37, 0x25, 0x3e, 0x51,
	0x8b, 0x99, 0x01, 0xf5, 0xe6, 0x2b, 0x12, 0x1f, 0xa8, 0xfa, 0x2a, 0xe2, 0x58, 0x95, 0xc3, 0xbc,
	0xf2, 0x16, 0x59, 0x27, 0xbb, 0x69, 0xbe, 0x3a, 0xa8, 0xfd, 0x30, 0x7b, 0x7f, 0x9b, 0x5c, 0x0c,
	0x81, 0xae, 0xdb, 0x19, 0x96, 0x32, 0x5e, 0x13, 0xe7, 0xae, 0x3a, 0xf6, 0x31, 0xa0, 0x2c, 0x85,
	0xd9, 0xa7, 0x27, 0x7b, 0x38, 0xc1, 0xfd, 0xad, 0xea, 0x8c, 0xa1, 0xa5, 0x2b, 0xaa, 0x17, 0x58,
	0xbe, 0xa2, 0xc4, 0x67, 0x5c, 0x8f, 0x3d, 0x5d, 0x7e, 0xb3, 0x19, 0xd5, 0xdf, 0x03, 0xb3, 0x7f,
	0x97, 0xb4, 0xff, 0x90, 0xe7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xb1, 0xff, 0x07, 0xb1,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonitoringServiceClient is the client API for MonitoringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitoringServiceClient interface {
	GetStatus(ctx context.Context, in *Void, opts ...grpc.CallOption) (*MonitoringResponse, error)
}

type monitoringServiceClient struct {
	cc *grpc.ClientConn
}

func NewMonitoringServiceClient(cc *grpc.ClientConn) MonitoringServiceClient {
	return &monitoringServiceClient{cc}
}

func (c *monitoringServiceClient) GetStatus(ctx context.Context, in *Void, opts ...grpc.CallOption) (*MonitoringResponse, error) {
	out := new(MonitoringResponse)
	err := c.cc.Invoke(ctx, "/models.MonitoringService/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitoringServiceServer is the server API for MonitoringService service.
type MonitoringServiceServer interface {
	GetStatus(context.Context, *Void) (*MonitoringResponse, error)
}

// UnimplementedMonitoringServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMonitoringServiceServer struct {
}

func (*UnimplementedMonitoringServiceServer) GetStatus(ctx context.Context, req *Void) (*MonitoringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}

func RegisterMonitoringServiceServer(s *grpc.Server, srv MonitoringServiceServer) {
	s.RegisterService(&_MonitoringService_serviceDesc, srv)
}

func _MonitoringService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.MonitoringService/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServiceServer).GetStatus(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _MonitoringService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.MonitoringService",
	HandlerType: (*MonitoringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _MonitoringService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster_status_response.proto",
}
